### ISSUE TITLE
tinysearch index needs an update

### ISSUE THREAD

**Issue by Ricket** [mre/endler.dev#5]
Your [tinysearch article](https://endler.dev/2019/tinysearch/) is on HN, but I played around with your search box and was confused about obvious missing search results at first, until I found that your index was last updated 8 months ago.

**Comment by mre** [comment]
Oh yeah,
kudos for not giving up and finding the root-cause. We'll have to add the tinysearch creation to the Github Actions pipeline [here](https://github.com/mre/mre.github.io/blob/source/.github/workflows/ci.yml). Right now it's a manual process and I forget or I'm too lazy. 😆 Would you like to give it a shot?

**Comment by Ricket** [comment]
No thanks, I'm not interested and too busy lately.

**Comment by mre** [comment]
No worries, I'll get to it eventually. Thanks for the report. 👍

**Comment by mre** [comment]
At long last the index is finally updated. 😆 Guess we can close this.
Thanks again for letting me know @Ricket.
