### ISSUE TITLE
Table formating on "about" page is broken

### ISSUE THREAD

**Issue by gernotstarke** [mre/endler.dev#9]
Matthias,

on https://endler.dev/about the table layout is broken.

Please forgive me - I'm currently too lazy to open a PR for it:

What I see on the page is:

----
Here's a list of some Open Source projects I maintain:

| Repository | Stars | | :--------- | ----: | | analysis-tools-dev/static-analysis | 7900 ★ | | mre/idiomatic-rust | 2061 ★ | | tinysearch/tinysearch | 1346 ★ | | mre/the-coding-interview |

----

kind regards and a merry xmas from Cologne ...

**Comment by mre** [comment]
Aye thanks for creating the issue. I've also noticed this in the past but I have no clue what's going on yet. :grin:
When I run `make deploy` from the command line the formatting looks good but when GitHub actions runs `make deploy` then it's getting botched. Zola version should be the same. Could be that GitHub escapes the stats while they are being included into the template. 
Anyway merry Christmas to you too. 🎄⛄

**Comment by mre** [comment]
This is resolved now. The [diff is here](https://github.com/mre/endler.dev/commit/080870cdc7917a022d3186ad7f4526f679a5a424) if anyone is interested.

Basically the previous implementation depended on undefined behavior in zola. The was no guarantee that the included markdown file was interpreted as such. The solution was to include a proper markdown file (with the correct extension and a frontmatter) and then do a little dance in the script to trim away the frontmatter before rendering: `{{ data | split(pat="+++") | nth(n=2) | markdown | safe }}`.

Thanks a lot for reporting the bug @gernotstarke. Much appreciated!
